config/routes.rb
Rails.application.routes.draw do
  resources :user_news_articles
  resources :news_articles
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  delete '/sessions/reset_page_count', to: 'sessions#reset_page_view_cookie', as: 'page_reset'
  delete '/sessions/logout', to: 'sessions#logout', as: 'logout'
  get '/sessions/new', to: 'sessions#new', as: 'new_login'
  post '/sessions/create', to: 'sessions#create', as: 'login'
  get '/sessions/show', to: 'sessions#show', as: 'current_user'
  # get '/user_news_articles/show', to: 'user_news_articles#show', as: 'recent_user'

  # delete '/user_news_articles/destroy', to: 'user_news_articles#destroy', as: 'delete_article'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/news_article.rb
class NewsArticle < ApplicationRecord
  has_many :user_news_articles
  has_many :users, through: :user_news_articles
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_news_articles
  has_many :news_articles, through: :user_news_articles

<<<<<<< HEAD
  validates :name, presence: true
  validates :age, presence: true
  validates :age, numericality: { greater_than: 13 }
=======
    validates :name, presence: true
    validates :name, uniqueness: true
    validates :age, presence: true
    validates :age, numericality: {greater_than: 13}
>>>>>>> 3be2dacdf7e299ee0d6f13b33598071f3cfde69b

  has_secure_password
end

app/models/user_news_article.rb
class UserNewsArticle < ApplicationRecord
  belongs_to :user
  belongs_to :news_article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user
  before_action :authorized

  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end

  def authorized
    redirect_to new_user_path unless set_current_user
  end
end

app/controllers/news_articles_controller.rb
class NewsArticlesController < ApplicationController
  skip_before_action :authorized, only: %i[index show]

  def index
    @news_articles = NewsArticle.all
  end

  def show
    @news_article = NewsArticle.find(params[:id])

    if session[:view_count]
      session[:view_count] = session[:view_count] + 1
    else
      session[:view_count] = 1
    end
  end

  def update
    @news_article = UserNewsArticle.find(params[:id])
    @news_article.update(news_params)
    redirect_to news_article_path(@news_article)
  end

  def destroy
    @news_article = NewsArticle.find(params[:id])
    @news_article.destroy

    redirect_to news_articles_path
  end

  private

  def news_params
    params.require[:news_articles].permit[
      :title,
      :published,
      :description,
      :category,
      :img_url,
      :url
    ]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: %i[new create]

  def reset_page_view_cookie
    session.delete(:view_count)

    redirect_back fallback_location: news_articles_path
  end

  def new; end

  def show
    @user = User.find_by(id: session[:user_id])
    redirect_to user_path(@user)
  end

  def create
    user = User.find_by(name: params[:session][:name])

    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to news_articles_path
    else
      flash[:error] = 'username or password is incorrect'
      redirect_to new_login_path
    end
  end

  def logout
    session.delete(:user_id)

    redirect_to new_user_path
  end
end

app/controllers/user_news_articles_controller.rb
class UserNewsArticlesController < ApplicationController
  def index
    @user_news_articles = UserNewsArticle.all
  end

  def show
    find_user_news_article
    # redirect_to user_path(@user)
  end

  def new
    @user_news_article = UserNewsArticle.new
  end

  def edit
    find_user_news_article
  end

  def create
    user_news_article =
      @current_user.user_news_articles.create(user_news_params)
    if user_news_article.valid?
      redirect_to user_path(@current_user)
    else
      flash[:my_errors] = user_news_article.errors.full_messages
      redirect_to new_user_news_article_path
    end
  end

  def update
    find_user_news_article
    @user_news_article.update(user_news_params)
    redirect_to user_news_article_path(@user_news_article)
  end

  def destroy
    user_news_article = UserNewsArticle.find(params[:id])
    user_news_article.destroy
    redirect_to user_path(@current_user)
  end

  private

  def user_news_params
    params.require(:user_news_article).permit(
      :favorites,
      :date_added,
      :news_article_id
    )
  end

  def find_user_news_article
    @user_news_article = UserNewsArticle.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: %i[new create]
  def show
    find_user

    if @user == @current_user
      render :show
    else
      flash[:error] = 'can only see your profile'
      redirect_to users_path
    end
  end

  def new
    @user = User.new
  end

  def create
    user = User.create(user_params)
    if user.valid?
      session[:user_id] = user.id
      redirect_to news_articles_path
    else
      flash[:my_errors] = user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def edit
    find_user
  end

  def update
    find_user
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def destroy
    user = User.find_by(id: session[:user_id])
    user.news_articles.destroy
    redirect_to user_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :age, :password)
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_articles_helper.rb
module NewsArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_news_articles_helper.rb
module UserNewsArticlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LatestNewsProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      

      <div class='nav'>
        
          <img class='logo' src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Internet-news-reader.svg/600px-Internet-news-reader.svg.png" alt="mm" style="width:250px;height:250px;object-fit: cover;">
        
      </div>

      <ul>
        <li><%= link_to 'News Home', news_articles_path %></li>
        <li><%= link_to 'User Home', current_user_path %></li>
        <li><%= link_to 'Add Article to Favorites', new_user_news_article_path %></li>

        <% if @current_user %>
          <li class='right'>Welcome <%= @current_user.name %>!</li>
          <li class='right'><%= link_to "Log-Out", logout_path, method: :delete%></li>
        <% else %>
          <li class='right'><%= link_to 'Sign-Up', new_user_path %></li>
          <li class='right'><%= link_to 'Sign-In', new_login_path %></li>
        <% end %>
      </ul>


    <%= yield %>
  </body>
</html>

app/views/news_articles/index.html.erb
<div class="container text-center">
    <h1>Latest News Articles</h1>

        <ul class="article-list">
            <% @news_articles.each do |news_article| %>
                <li>
                    <div class="card" style="width: 18rem;">
                        <%if news_article.img_url == "None"%>
                            <%= image_tag 'No-image-found.jpg' %>
                        <%else%>
                            <img class="card-img-top" src="<%=news_article.img_url%>" alt="<%news_article.title%>">
                        <%end%>
                    <div class="card-body">
                    <h5 class="card-title"><%= link_to news_article.title, news_article %></h5>
                    </div>
                </li>
            <% end %>
            
        </ul>
</div>

app/views/news_articles/show.html.erb
<div class="container text-center">
    <% if  session[:view_count] <= 3 %>
        <h1 style="color: green;">You have <%= 3 - session[:view_count].to_i %> view left</h1>

        <h1>News Article Show Page</h1>
        <br>
        <br>
        <h4><%= @news_article.title %></h4>
        <p>Date Published: <%= @news_article.published %></p>
        <p>Description: <%= @news_article.description %></p>
        <p>Category: <%= @news_article.category %></p>
        <p><img class="show-img" src="<%= @news_article.img_url %>" alt="<%= @news_article.title %>" style="width:500px;height:250px;object-fit: cover;"></p>
        <p>URL: <%= link_to @news_article.url, "#{@news_article.url}", :target => "_blank" %></p>

        <%= link_to 'Home page', news_articles_path %>

    <% else %>
        <h1>Continue After Paying $5.00</h1>
        <%= button_to "Pay $5", page_reset_path, method: :delete %>
    <% end %>
    
</div>

app/views/user_news_articles/edit.html.erb
<div class="container text-center">
<h1>Add News Article</h1>

<%= form_for @user_news_article do |f| %>
    <%= f.label :news_article_id %>
    <%= f.collection_select :news_article_id, NewsArticle.all, :id, :title%>
    <%= f.submit %>
<% end %>
</div>

app/views/user_news_articles/index.html.erb
<div class="container text-center">
<h1>My News Articles</h1>

<ul>
    <% @user_news_articles.each do |user_news_article| %>
        <li><%= link_to user_news_article.title, user_news_article %></li>
    <% end %>
</ul>
</div>

app/views/user_news_articles/new.html.erb
<div class="container text-center">
<h1>Add News Article</h1>

<%= form_for @user_news_article do |f| %>
    <%= f.label :news_article_id %>
    <%= f.collection_select :news_article_id, NewsArticle.all, :id, :title%>
    <%= f.submit "Add Article"%>
<% end %>
</div>

app/views/user_news_articles/show.html.erb
<div class="container text-center">
<h1>My News Article Show Page</h1>

<p>Title: <%= link_to @user_news_article.news_article.title, news_article_path(@user_news_article.news_article) %></p>


<%= link_to 'User Profile', user_path(@user_news_article.user) %>
</div>

app/views/users/edit.html.erb
<div class="container text-center">
<h1>Create New User</h1>

<%= form_for @user do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :age %>
<%= f.number_field :age %>
<%= f.submit %>

<% end %>
</div>

app/views/users/new.html.erb
<div class="container text-center">
<h1>Create New User</h1>

<% if flash[:my_errors] %>
  <% flash[:my_errors].each do |error| %>
    <p style="color: red;"><%= error %></p>
  <% end %>
<% end %>

<%= form_for @user do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :age %>
    <%= f.number_field :age %>

    <%= f.label :password%>
    <%= f.text_field :password%>

    <%= f.submit %>

<% end %>
</div>

app/views/users/show.html.erb
<div class="container text-center">
<h1>User Show Page</h1>

<p>Name: <%= @user.name %></p>
<p>Age: <%= @user.age %></p>

<h2>My News Articles</h2>

    <% if @user.user_news_articles.empty?%>
        <p>You have no favorites</p> 
        <br>
        <p>Please visit the 'Add Article to Favorites'</p>
    <% else %>
        <% @user.user_news_articles.each do |user_news_article| %>
        <li><%= link_to user_news_article.news_article.title, news_article_path(user_news_article) %> <%= button_to "X", "/user_news_articles/#{user_news_article.id}", method: :delete %></li>
         
        <% end %> 
    <% end %>

</div>